batch_size: 1024
entropy_coef: 0.1
env_name: brax-halfcheetah-v0
episode_length: 1000
epoch_repeat: 4
epsilon: 0.3
gamma: 0.99
hidden_size: 192
lamb: 0.95
num_envs: 2048
optim: !!python/name:torch.optim.adamw.AdamW ''
policy_lr: 0.0001
samples_per_epoch: 10
value_lr: 0.001
